// Generated by run.mjs: actual unchanged method bodies, portable type scaffolding.
#[derive(Debug, PartialEq)]
pub enum CompositorTargetKind {
    /// Host target is the whole Tauri WebviewWindow.
    /// Occluded on macOS because WKWebView sits in front of the window-level layer.
    RootWebviewWindow,
    /// Dedicated platform layer-backed child view positioned relative to the webview (macOS NSView).
    NativeChildView,
    /// Dedicated Windows child composition target / window (DirectComposition / Win32 HWND).
    WindowsChildWindow,
    /// Dedicated Linux child composition target / window (X11 subwindow / Wayland subsurface).
    LinuxChildWindow,
    /// Fallback / unsupported platform target.
    UnsupportedFallback,
}
#[derive(Debug)]
pub struct PlatformCompositorDescriptor {
    pub target_kind: CompositorTargetKind,
    pub pointer_transparent: bool,
    pub layer_backed: bool,
}
#[derive(Debug)]
pub enum NativeTerminalError { GpuPipelineError(String) }
impl PlatformCompositorDescriptor {
pub fn validate_desktop_composition(&self) -> Result<(), NativeTerminalError> {
        if self.target_kind == CompositorTargetKind::RootWebviewWindow {
            return Err(NativeTerminalError::GpuPipelineError(
                "Root WebviewWindow cannot be used as native terminal composition target because WKWebView occludes the layer".into(),
            ));
        }
        if self.target_kind == CompositorTargetKind::UnsupportedFallback {
            return Err(NativeTerminalError::GpuPipelineError(
                "Unsupported platform for native terminal composition".into(),
            ));
        }
        match self.target_kind {
            CompositorTargetKind::NativeChildView => {
                if !self.layer_backed {
                    return Err(NativeTerminalError::GpuPipelineError(
                        "Native terminal composition target must be layer-backed".into(),
                    ));
                }
                if !self.pointer_transparent {
                    return Err(NativeTerminalError::GpuPipelineError(
                        "Native terminal child view must be pointer-transparent for web focus routing".into(),
                    ));
                }
            }
            CompositorTargetKind::WindowsChildWindow => {
                if !self.layer_backed {
                    return Err(NativeTerminalError::GpuPipelineError(
                        "Windows native terminal composition target is not layer-backed (child window clipping not established)".into(),
                    ));
                }
                if !self.pointer_transparent {
                    return Err(NativeTerminalError::GpuPipelineError(
                        "Windows native terminal child window is not pointer-transparent for web focus routing (child window clipping not established)".into(),
                    ));
                }
            }
            CompositorTargetKind::LinuxChildWindow => {
                if !self.layer_backed {
                    return Err(NativeTerminalError::GpuPipelineError(
                        "Linux native terminal composition target is not layer-backed (subsurface clipping not established)".into(),
                    ));
                }
                if !self.pointer_transparent {
                    return Err(NativeTerminalError::GpuPipelineError(
                        "Linux native terminal child window is not pointer-transparent for web focus routing (subsurface clipping not established)".into(),
                    ));
                }
            }
            CompositorTargetKind::RootWebviewWindow | CompositorTargetKind::UnsupportedFallback => {
                unreachable!()
            }
        }
        Ok(())
    }
}
struct WindowsCompositorTarget;
impl WindowsCompositorTarget {
pub fn descriptor(&self) -> PlatformCompositorDescriptor {
        PlatformCompositorDescriptor {
            target_kind: CompositorTargetKind::WindowsChildWindow,
            pointer_transparent: false,
            layer_backed: false,
        }
    }
}
#[test]
fn windows_platform_descriptor_passes_desktop_composition_validation() {
    let target = WindowsCompositorTarget;
    let descriptor = target.descriptor();
    println!("descriptor={descriptor:?}");
    descriptor.validate_desktop_composition().expect("platform descriptor must pass desktop composition validation");
}
